# mkdocs.yaml
 
# Site
site_name: Team Orange - Github Docs
site_author: Anders
site_dir: _site
repo_url: https://github.com/Anders-AS/docs
repo_name: Anders-AS/docs
docs_dir: docs
 
# Plugins
plugins:
  - mermaid2
  - search
 
# Navigation
nav:
  - Home: index.md
  - Guides:
      - Private DNS Zone migration guide: privatednszone-migration.md
 
# Theme
theme:
  name: material
  language: en
  logo: assets/orange-logo-small.png
  icon:
    repo: fontawesome/brands/github
 
  # Features
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.links
    - content.code.annotation
    - content.code.copy
 
  # Palette & Colours
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: orange
 
  # Extensions
  markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: tag:yaml.org,2002:python/name:materialx.emoji.twemoji
        emoji_generator: tag:yaml.org,2002:python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: tag:yaml.org,2002:python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

# Extra
extra_css:
- stylesheets/logo.css
 